---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-papaya-issuer
  namespace: papaya
rules:
  - apiGroups: ['']
    resources: ['serviceaccounts/token']
    resourceNames: ['vault-papaya-issuer']
    verbs: ['create']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-papaya-issuer
  namespace: papaya
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-papaya-issuer


